language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - cd ..
  - cd reboot2/src
  - cp reboot2/settings/local.sample.env my_proj/settings/local.env
  - python manage.py migrate
script:
  - python manage.py test profiles
