language: python
python:
  - "3.4"
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt
  - cd ..
  - cd reboot2/src
  - cp reboot2/settings/local.sample.env reboot2/settings/local.env
  - python manage.py migrate
script:
  - python manage.py test
after_success:
  - codecov
