language: python
python:
  - "3.4"
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt
  - cd ..
  - cd reboot2/src
  - cp reboot2/settings/local.sample.env reboot2/settings/local.env
  - python manage.py migrate
script:
  - python manage.py test profiles
  - python manage.py test polls
  - cd reboot2/src/profiles
  - coverage run tests.py
  - cd reboot2/src/polls
  - coverage run tests.py
after_success:
  - codecov
